#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: autogen
# autospec version: v20
# autospec commit: f35655a
#
Name     : cups-filters
Version  : 1.28.16
Release  : 80
URL      : https://www.openprinting.org/download/cups-filters/cups-filters-1.28.16.tar.bz2
Source0  : https://www.openprinting.org/download/cups-filters/cups-filters-1.28.16.tar.bz2
Summary  : Library for de/embedding fonts to pdf
Group    : Development/Tools
License  : BSD-4-Clause GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 MIT
Requires: cups-filters-bin = %{version}-%{release}
Requires: cups-filters-data = %{version}-%{release}
Requires: cups-filters-lib = %{version}-%{release}
Requires: cups-filters-man = %{version}-%{release}
Requires: cups-filters-services = %{version}-%{release}
BuildRequires : cups-dev
BuildRequires : dejavu-fonts
BuildRequires : file
BuildRequires : ghostscript-dev
BuildRequires : glib-dev
BuildRequires : gnutls-dev
BuildRequires : krb5-dev
BuildRequires : openldap-dev
BuildRequires : pkgconfig(com_err)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(gio-unix-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libexif)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(poppler-cpp)
BuildRequires : pkgconfig(zlib)
BuildRequires : pypi(packaging)
BuildRequires : qpdf-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-fix-systemd-service-file.patch
Patch2: 0001-Move-to-c-17.patch

%description
--------------------------------------------------------
Looking for compile instructions?  Read the file "INSTALL.txt"
instead...

%package bin
Summary: bin components for the cups-filters package.
Group: Binaries
Requires: cups-filters-data = %{version}-%{release}
Requires: cups-filters-services = %{version}-%{release}

%description bin
bin components for the cups-filters package.


%package data
Summary: data components for the cups-filters package.
Group: Data

%description data
data components for the cups-filters package.


%package dev
Summary: dev components for the cups-filters package.
Group: Development
Requires: cups-filters-lib = %{version}-%{release}
Requires: cups-filters-bin = %{version}-%{release}
Requires: cups-filters-data = %{version}-%{release}
Provides: cups-filters-devel = %{version}-%{release}
Requires: cups-filters = %{version}-%{release}

%description dev
dev components for the cups-filters package.


%package doc
Summary: doc components for the cups-filters package.
Group: Documentation
Requires: cups-filters-man = %{version}-%{release}

%description doc
doc components for the cups-filters package.


%package extras
Summary: extras components for the cups-filters package.
Group: Default

%description extras
extras components for the cups-filters package.


%package lib
Summary: lib components for the cups-filters package.
Group: Libraries
Requires: cups-filters-data = %{version}-%{release}

%description lib
lib components for the cups-filters package.


%package man
Summary: man components for the cups-filters package.
Group: Default

%description man
man components for the cups-filters package.


%package services
Summary: services components for the cups-filters package.
Group: Systemd services
Requires: systemd

%description services
services components for the cups-filters package.


%prep
%setup -q -n cups-filters-1.28.16
cd %{_builddir}/cups-filters-1.28.16
%patch -P 1 -p1
%patch -P 2 -p1
pushd ..
cp -a cups-filters-1.28.16 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1727392621
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%autogen --disable-static --disable-avahi \
--without-tiff \
--disable-ijs \
--disable-mutool \
--without-rcdir \
--disable-braille \
--with-fontdir=/usr/share/defaults/fonts/conf.d \
--with-pdftops=pdftocairo \
--enable-driverless \
--enable-auto-setup-driverless
make  %{?_smp_mflags}

pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%autogen --disable-static --disable-avahi \
--without-tiff \
--disable-ijs \
--disable-mutool \
--without-rcdir \
--disable-braille \
--with-fontdir=/usr/share/defaults/fonts/conf.d \
--with-pdftops=pdftocairo \
--enable-driverless \
--enable-auto-setup-driverless
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1727392621
rm -rf %{buildroot}
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system
install -p -m 644 utils/cups-browsed.service %{buildroot}/usr/lib/systemd/system/cups-browsed.service
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib/cups/backend/beh
/V3/usr/lib/cups/backend/implicitclass
/V3/usr/lib/cups/backend/parallel
/V3/usr/lib/cups/backend/serial
/V3/usr/lib/cups/driver/driverless
/V3/usr/lib/cups/filter/bannertopdf
/V3/usr/lib/cups/filter/commandtoescpx
/V3/usr/lib/cups/filter/commandtopclx
/V3/usr/lib/cups/filter/foomatic-rip
/V3/usr/lib/cups/filter/gstoraster
/V3/usr/lib/cups/filter/imagetopdf
/V3/usr/lib/cups/filter/imagetoraster
/V3/usr/lib/cups/filter/pdftopdf
/V3/usr/lib/cups/filter/pdftops
/V3/usr/lib/cups/filter/pdftoraster
/V3/usr/lib/cups/filter/rastertoescpx
/V3/usr/lib/cups/filter/rastertopclx
/V3/usr/lib/cups/filter/rastertopdf
/V3/usr/lib/cups/filter/rastertops
/V3/usr/lib/cups/filter/sys5ippprinter
/V3/usr/lib/cups/filter/texttopdf
/V3/usr/lib/cups/filter/texttotext
/usr/lib/cups/backend/beh
/usr/lib/cups/backend/driverless
/usr/lib/cups/backend/driverless-fax
/usr/lib/cups/backend/implicitclass
/usr/lib/cups/backend/parallel
/usr/lib/cups/backend/serial
/usr/lib/cups/driver/driverless
/usr/lib/cups/driver/driverless-fax
/usr/lib/cups/filter/bannertopdf
/usr/lib/cups/filter/commandtoescpx
/usr/lib/cups/filter/commandtopclx
/usr/lib/cups/filter/foomatic-rip
/usr/lib/cups/filter/gstopdf
/usr/lib/cups/filter/gstopxl
/usr/lib/cups/filter/gstoraster
/usr/lib/cups/filter/imagetopdf
/usr/lib/cups/filter/imagetops
/usr/lib/cups/filter/imagetoraster
/usr/lib/cups/filter/pdftopdf
/usr/lib/cups/filter/pdftops
/usr/lib/cups/filter/pdftoraster
/usr/lib/cups/filter/rastertoescpx
/usr/lib/cups/filter/rastertopclm
/usr/lib/cups/filter/rastertopclx
/usr/lib/cups/filter/rastertopdf
/usr/lib/cups/filter/rastertops
/usr/lib/cups/filter/sys5ippprinter
/usr/lib/cups/filter/texttopdf
/usr/lib/cups/filter/texttops
/usr/lib/cups/filter/texttotext

%files bin
%defattr(-,root,root,-)
/usr/bin/driverless
/usr/bin/driverless-fax
/usr/bin/foomatic-rip

%files data
%defattr(-,root,root,-)
/usr/share/cups/banners/classified
/usr/share/cups/banners/confidential
/usr/share/cups/banners/form
/usr/share/cups/banners/secret
/usr/share/cups/banners/standard
/usr/share/cups/banners/topsecret
/usr/share/cups/banners/unclassified
/usr/share/cups/charsets/pdf.utf-8
/usr/share/cups/charsets/pdf.utf-8.heavy
/usr/share/cups/charsets/pdf.utf-8.simple
/usr/share/cups/data/classified.pdf
/usr/share/cups/data/confidential.pdf
/usr/share/cups/data/default-testpage.pdf
/usr/share/cups/data/default.pdf
/usr/share/cups/data/form_english.pdf
/usr/share/cups/data/form_english_in.odt
/usr/share/cups/data/form_russian.pdf
/usr/share/cups/data/form_russian_in.odt
/usr/share/cups/data/secret.pdf
/usr/share/cups/data/standard.pdf
/usr/share/cups/data/testprint
/usr/share/cups/data/topsecret.pdf
/usr/share/cups/data/unclassified.pdf
/usr/share/cups/drv/cupsfilters.drv
/usr/share/cups/mime/cupsfilters-ghostscript.convs
/usr/share/cups/mime/cupsfilters-poppler.convs
/usr/share/cups/mime/cupsfilters.convs
/usr/share/cups/mime/cupsfilters.types
/usr/share/cups/ppdc/escp.h
/usr/share/cups/ppdc/pcl.h
/usr/share/ppd/cupsfilters/Fuji_Xerox-DocuPrint_CM305_df-PDF.ppd
/usr/share/ppd/cupsfilters/Generic-PDF_Printer-PDF.ppd
/usr/share/ppd/cupsfilters/HP-Color_LaserJet_CM3530_MFP-PDF.ppd
/usr/share/ppd/cupsfilters/Ricoh-PDF_Printer-PDF.ppd
/usr/share/ppd/cupsfilters/pxlcolor.ppd
/usr/share/ppd/cupsfilters/pxlmono.ppd

%files dev
%defattr(-,root,root,-)
/usr/include/cupsfilters/colord.h
/usr/include/cupsfilters/colormanager.h
/usr/include/cupsfilters/driver.h
/usr/include/cupsfilters/image.h
/usr/include/cupsfilters/ipp.h
/usr/include/cupsfilters/pdftoippprinter.h
/usr/include/cupsfilters/ppdgenerator.h
/usr/include/cupsfilters/raster.h
/usr/include/fontembed/bitset.h
/usr/include/fontembed/embed.h
/usr/include/fontembed/fontfile.h
/usr/include/fontembed/iofn.h
/usr/include/fontembed/sfnt.h
/usr/lib64/libcupsfilters.so
/usr/lib64/libfontembed.so
/usr/lib64/pkgconfig/libcupsfilters.pc
/usr/lib64/pkgconfig/libfontembed.pc

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/cups\-filters/*

%files extras
%defattr(-,root,root,-)
/V3/usr/bin/cups-browsed
/usr/bin/cups-browsed

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libcupsfilters.so.1.0.0
/V3/usr/lib64/libfontembed.so.1.0.0
/usr/lib64/libcupsfilters.so.1
/usr/lib64/libcupsfilters.so.1.0.0
/usr/lib64/libfontembed.so.1
/usr/lib64/libfontembed.so.1.0.0

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/driverless.1
/usr/share/man/man1/foomatic-rip.1
/usr/share/man/man5/cups-browsed.conf.5
/usr/share/man/man8/cups-browsed.8

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/cups-browsed.service
